Repository uchicago-capp-30320/CivicLens, pull requests merged in 2024-05, with the labels that each got.

#146 124 sort the search by
  civiclens/regulations/views.py
  civiclens/templates/search_results.html
Labels: Front-End, Django

#147 70 filters for search results
  civiclens/regulations/static/css/base.css
  civiclens/regulations/views.py
  civiclens/templates/search_results.html
Labels: Front-End, Django

#164 163 build out qa checks on document data and ideally docket and comment data
  civiclens/collect/bulk_dl.py
Labels: Back-End

#193 Update settings.py
  civiclens/website/settings.py
Labels: Django

#198 Friday's update with Michael to make only a single graph
  civiclens/regulations/static/js/graph.js
Labels: Front-End

#202 Removed /regulations/ from url bar in Django and htmls
  civiclens/regulations/static/js/graph.js
  civiclens/regulations/urls.py
  civiclens/templates/home.html
  civiclens/templates/includes/footer.html
  civiclens/templates/includes/navigation.html
  civiclens/templates/search_page.html
  civiclens/templates/search_results.html
  civiclens/website/urls.py
Labels: Front-End, Django

#218 Limited representative/website provided comments to 5 comments, also cleaned up def document() in views.py
  civiclens/regulations/views.py
  civiclens/templates/document.html
Labels: Front-End, Django

#222 Deleted comment.html page from views.py, urls.py, and html
  civiclens/regulations/urls.py
  civiclens/regulations/views.py
  civiclens/templates/comment.html
Labels: Front-End, Django

#228 Instituted keeping the previous search and filters/sorts with forms.py & adding logging to views.py
  civiclens/collect/check_doc_status.py
  civiclens/regulations/forms.py
  civiclens/regulations/views.py
  civiclens/templates/search_page.html
  civiclens/templates/search_results.html
  civiclens/website/settings.py
Labels: Front-End, Django

#239 Integrate NLP Models into Search Queries, document.html, and search_results.html
  civiclens/regulations/views.py
  civiclens/templates/document.html
  civiclens/templates/search_results.html
Labels: Front-End, Django

#259 Fixed bugs, if/else around bad nlp title, added new search_page commo…
  civiclens/regulations/views.py
  civiclens/templates/document.html
  civiclens/templates/search_page.html
  civiclens/templates/search_results.html
Labels: Front-End, Django

#289 281 cleanup views documenthtml searchpagehtml and searchresultshtml
  civiclens/regulations/static/js/search_utils.js
  civiclens/regulations/views.py
  civiclens/templates/document.html
  civiclens/templates/layouts/base.html
  civiclens/templates/search_page.html
  civiclens/templates/search_results.html
Labels: Front-End, Django
